Repository JNU-econovation/EEOS-FE, pull requests merged in 2024-11, with the labels that each got.

#125 [FIX] 올바르게 출석체크 버튼이 활성화 되도록 수정
  FE/src/components/programDetail/userAttendModal/AttendStatusView.tsx
  FE/src/components/programDetail/userAttendModal/UserAttendModal.tsx
  FE/src/hooks/query/useProgramQuery.ts
Labels: bug

#127 [CHORE] github url의 validation을 전부 백엔드로 위임
  FE/src/components/common/form/program/CreateForm.tsx
  FE/src/components/programEdit/EditForm.tsx
  FE/src/utils/convert.ts
Labels: chore

#136 [FEAT] attendStatus에 따른 refetchInterval을 통한 polling 구현
  FE/src/hooks/query/useMemberQuery.ts
Labels: feature🔥
