Repository JNU-econovation/EEOS-FE, pull requests merged in 2024-12, with the labels that each got.

#145 [FEAT] 질문 입력 창 크기 조절 추가
  FE/src/components/common/CheckBox/CheckBox.tsx
  FE/src/components/feature/detail/Dashboard/components/DashboardInput.tsx
Labels: feature🔥

#147 [FEAT] 대댓글의 대댓글 기능 추가
  FE/src/components/feature/detail/Dashboard/components/ChatList.tsx
  FE/src/components/feature/detail/Dashboard/components/ReplyChat.tsx
  FE/src/hooks/query/useQuestionQuery.ts
  FE/src/utils/question.ts
Labels: feature🔥

#148 [FIX] polling issue 해결
  FE/src/hooks/query/useProgramQuery.ts
Labels: fix🔧

#150 [FIX] onSuccess invalidateQueries 로직 추가
  FE/src/hooks/query/useProgramQuery.ts
Labels: fix🔧

#152 [FIX] attendMode invalidateQueries 적용
  FE/src/hooks/query/useProgramQuery.ts
Labels: bug 🐛, fix🔧

#153 [RELEASE] release 3.0.1 출석상태 polling 기능 추가
  FE/package.json
  FE/src/apis/__test__/program.test.ts
  FE/src/apis/__test__/question.test.ts
  FE/src/apis/question.ts
  FE/src/app/(admin)/admin/detail/[programId]/page.tsx
  FE/src/app/(guest)/guest/detail/[programId]/page.tsx
  FE/src/app/(private)/(program)/detail/[programId]/page.tsx
  FE/src/components/common/CheckBox/CheckBox.tsx
  FE/src/components/common/dashboard/ChatBox.tsx
  FE/src/components/common/form/program/CreateForm.tsx
  FE/src/components/common/tabs/tab/Tab.tsx
  FE/src/components/common/tabs/tab/TabAsChild/TabAsChild.tsx
  FE/src/components/common/tabs/tab/TabCompound/TabCompound.tsx
  FE/src/components/feature/detail/Dashboard/BlurDashboard.tsx
  FE/src/components/feature/detail/Dashboard/ProgramDashboardSection.tsx
  FE/src/components/feature/detail/Dashboard/TeamsTab.tsx
  FE/src/components/feature/detail/Dashboard/components/Chat.tsx
  FE/src/components/feature/detail/Dashboard/components/ChatList.tsx
  FE/src/components/feature/detail/Dashboard/components/DashboardContent.tsx
  FE/src/components/feature/detail/Dashboard/components/DashboardInput.tsx
  FE/src/components/feature/detail/Dashboard/components/ReplyChat.tsx
  FE/src/components/feature/detail/attendee/AttendeeInfo.container.tsx
  FE/src/components/feature/detail/attendee/AttendeeInfo.loader.tsx
  FE/src/components/feature/detail/attendee/AttendeeInfo.tsx
  FE/src/components/feature/detail/attendee/AttendeeStatus.tsx
  FE/src/components/feature/detail/attendee/BluredAttedee.tsx
  FE/src/components/feature/detail/loader/ProgramDetail.skeleton.tsx
  FE/src/components/feature/detail/loader/ProgramHeader.skeleton.tsx
  FE/src/components/feature/detail/presentation/ProgramPresentationsSection.tsx
  FE/src/components/feature/detail/program/EditAndDeleteButton.tsx
  FE/src/components/feature/detail/program/ProgramAttendStatusManageSection.tsx
  FE/src/components/feature/detail/program/ProgramDetailSection.tsx
  FE/src/components/feature/detail/program/ProgramHeaderSection.tsx
  FE/src/components/feature/detail/userAttendModal/AttendStatusModal.loader.tsx
  FE/src/components/feature/detail/userAttendModal/AttendStatusView.tsx
  FE/src/components/feature/detail/userAttendModal/AttendToggleLabel.tsx
  FE/src/components/feature/detail/userAttendModal/LoginModal.tsx
  FE/src/components/feature/detail/userAttendModal/UserAttendModal.container.tsx
  FE/src/components/feature/detail/userAttendModal/UserAttendModal.tsx
  FE/src/components/programDetail/program/DashboardCompound/Board/common/ChatList.tsx
  FE/src/components/programDetail/program/DashboardCompound/DashboardWrapper.tsx
  FE/src/components/programDetail/program/DashboardCompound/Form.tsx
  FE/src/components/programDetail/program/DashboardCompound/TeamTab.tsx
  FE/src/components/programDetail/program/ProgramDashboard.tsx
  FE/src/components/programDetail/program/ProgramDetail.tsx
  FE/src/components/programDetail/program/ProgramInfo.loader.tsx
  FE/src/components/programDetail/program/ProgramInfo.tsx
  FE/src/hooks/query/useMemberQuery.ts
  FE/src/hooks/query/useProgramQuery.ts
  FE/src/hooks/query/useQuestionQuery.ts
  FE/src/hooks/useAccess.ts
  FE/src/hooks/usePrograms.ts
  FE/src/store/dashboardAtoms.ts
  FE/src/utils/convert.ts
  FE/src/utils/question.ts
Labels: release🎉

#155 [FIX] 올바르게 출석 상태에 따라서 출석 버튼이 활성화 되지 않던 버그 수정
  FE/src/components/feature/detail/userAttendModal/UserAttendModal.tsx
  FE/src/constants/ATTEND_STATUS.ts
  FE/src/utils/__test__/program.test.ts
  FE/src/utils/program.ts
Labels: fix🔧

#156 [RELEASE] release 3.0.2 출석 버튼 버그 수정
  FE/src/components/feature/detail/userAttendModal/UserAttendModal.tsx
  FE/src/constants/ATTEND_STATUS.ts
  FE/src/utils/__test__/program.test.ts
  FE/src/utils/program.ts
Labels: release🎉
